apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hello-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-hello-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
